### ISSUE TITLE
剩余 monorepo 改造内容

### ISSUE THREAD

**Issue by linningmii** [alibaba/pont#102]
目前monorepo的改造工作只做了文件的迁移和lerna的引入，和PR同学讨论了之后觉得后续通过几个PR持续更新更好，避免单个PR内容过大

目前的发布方式还是手动cd到对应的package下，维持原有的发布方式

后续剩余工作量还比较多
- [ ] 全局依赖迁移
- [ ] lerna体系发布
- [ ] 补充UnitTest

_Originally posted by @linningmii in https://github.com/alibaba/pont/pull/99#issuecomment-533761617_

**Comment by ShawDanon** [comment]
# 关于改造建议

## 关于发布流程优化

## 现有

流程：cd 到需要发布的包通过 tsc 进行 build，然后 lerna publish 进行发布。
缺点：
1、手动操作过多，现在只继承两个包还好，如果管理数十个包这个流程会疯掉的。
2、忘操作，记不清是不是打过包了，可能出现漏打包进行发布。

## 优化

流程：引入 father-build（蚂蚁云谦开发，umi 同为 lerna 架构）进行打包。
优化优点：一条对命令 package 所有包进行打包，在加上 `npm run build && lerna publish`进行发布

## 关于持续集成流程移动到根目录建议

### 现状

core 中有提交检查，但是这个提交检查需要 core 安装了 modules 才能生效。

## 优化

将提交检查移动到目录，在本项目装包后就能进行检查，更符合直觉。

## 关于根目录脚本命令添加建议

装包必备： "bootstrap": "lerna bootstrap",
打包必备："build": "father-build",
发布必备： "publish": "npm run build && lerna publish",
## 我认为还需要的解决方案
1、release方案、
2、代码检查
3、持续集成
4、文档（docz）
@inJs @linningmii

**Comment by inJs** [comment]
我有几个疑问：

+ 打包环节目前有哪些方案？目前可选的方案？为什么选择 `father-build` ？
