### ISSUE TITLE
自定义代码生成器文档404

### ISSUE THREAD

**Issue by Slebee** [alibaba/pont#108]
## What happens(发生了什么)?

自定义代码生成器文档404

## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.

**Expected behavior(预期行为)** 1. 2.

## Context(上下文)

- **pont Version**:
- **Node Version**:
- **Platform(操作系统平台)**:

**Comment by linningmii** [comment]
Fixed by #112
