### ISSUE TITLE
I ran into VSIXInstaller.NoApplicableSKUsException error when installing this plugin

### ISSUE THREAD

**Issue by mobilesite** [alibaba/pont#111]
I got this error when I install this plugin. How can I work through it?

My VS Code version is 1.23.1 and my system is Win 10.

Error log:

2019/10/26 20:35:44 - Microsoft VSIX Installer
2019/10/26 20:35:44 - -------------------------------------------
2019/10/26 20:35:44 - Initializing Install...
2019/10/26 20:35:44 - 扩展详细信息...
2019/10/26 20:35:44 - 	Identifier         : vscode-pont
2019/10/26 20:35:44 - 	Name               : pont
2019/10/26 20:35:44 - 	Author             : jasonHzq
2019/10/26 20:35:44 - 	Version            : 0.2.5
2019/10/26 20:35:44 - 	Description        : 
2019/10/26 20:35:44 - 	Locale             : en-US
2019/10/26 20:35:44 - 	MoreInfoURL        : 
2019/10/26 20:35:44 - 	InstalledByMSI     : False
2019/10/26 20:35:44 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2019/10/26 20:35:44 - 
2019/10/26 20:35:44 - 	SignatureState     : Unsigned
2019/10/26 20:35:44 - 	支持的产品              : 
2019/10/26 20:35:44 - 		Microsoft.VisualStudio.Code
2019/10/26 20:35:44 - 			Version : 
2019/10/26 20:35:44 - 
2019/10/26 20:35:44 - 	引用                 : 
2019/10/26 20:35:44 - 签名详细信息...
2019/10/26 20:35:44 - 	Extension is not signed.
2019/10/26 20:35:44 - 
2019/10/26 20:35:44 - 正在搜索适用的产品...
2019/10/26 20:35:44 - 找到的已安装产品 - Microsoft Visual Studio Professional 2015
2019/10/26 20:35:44 - 找到的已安装产品 - Microsoft Visual Studio Community 2015
2019/10/26 20:35:44 - 找到的已安装产品 - Microsoft Visual Studio 2015 Shell (Integrated)
2019/10/26 20:35:44 - 找到的已安装产品 - 全局位置
2019/10/26 20:35:44 - VSIXInstaller.NoApplicableSKUsException: 此扩展不能安装在任何当前安装的产品上。
   在 VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   在 VSIXInstaller.App.InitializeInstall()
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()

**Comment by linningmii** [comment]
Seems like you are using an old vscode version, the newest version now is 1.39.2, could you try the latest stable version? We have never test the compatibility of old vscode

**Comment by linningmii** [comment]
> Seems like you are using an old vscode version, the newest version now is 1.39.2, could you try the latest stable version? We have never test the compatibility of old vscode

You may also try to install the plugin via extensions module in vscode, not by double-clicking the .vsix binary file
