### ISSUE TITLE
当后端的方法名称包含js的关键字的时候，生成结果会出现问题

### ISSUE THREAD

**Issue by yzStrive** [alibaba/pont#113]
## What happens(发生了什么)?
后端的某个方法名称为js关键字，导致生成结果出现问题
# Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.

**Expected behavior(预期行为)** 期望过滤掉关键字，当出现关键字时，用非关键字替换掉

## Context(上下文)

- **pont Version**:0.2.5
- **Node Version**:v10.15.3
- **Platform(操作系统平台)**:macOS Mojave 10.14.2

**Comment by 540240126** [comment]
+1

**Comment by jasonHzq** [comment]
我们对主要关键字已经做了替换，你这里是哪些关键字出了问题？

**Comment by 540240126** [comment]
@jasonHzq 我这里是后端取了个function的名称，但是function在js里面是关键字就报错了

**Comment by jasonHzq** [comment]
已修复待发布
