### ISSUE TITLE
建议pont-engine 增加release log，对一直关注pont项目的同学会比较友好

### ISSUE THREAD

**Issue by duibu05** [alibaba/pont#116]
## Background(背景)

最近一直在关注pont项目，今天发现pont-engine发布了新的release，想找release log看看变化，结果没找到😅

## Proposal(建议)

建议维护release log，标注本次release包含哪些bug fixes及其对应的issue，有哪些new feature，是否有breaking changes等等

**Comment by jasonHzq** [comment]
已增加
