### ISSUE TITLE
自动生成的Params，Response，TS报错

### ISSUE THREAD

**Issue by LbhFront-end** [alibaba/pont#117]
## What happens(发生了什么)?

自动生成的Params，Response会报错

```ts
// pontTemplate.ts
import { CodeGenerator, Interface } from 'pont-engine';

export default class MyGenerator extends CodeGenerator {
  getInterfaceContent(inter: Interface) {
    const paramsCode = inter.getParamsCode();
    const bodyParams = inter.getBodyParamsCode();
    const method = inter.method.toUpperCase();
    const requestParams = bodyParams ? `params:Params,  bodyParams: ${bodyParams}` : `params:Params`;
    const urlReg = new RegExp('(\{([0-9a-zA-Z_]*)\})', 'g')

    return `
        /**
        * @description ${inter.description}
        */

      import * as defs from '../../baseClass';
      import MRequest from '../../../utils/request';

      export ${paramsCode}
      export type Response = ${inter.responseType};

      export async function request(${requestParams}): Promise<Response>{
        return MRequest(
          \`${inter.path.replace(urlReg, "$${params.$2}")}/\${params}\`,
          ${
      method !== 'GET'
        ? `{
                method:"${method}",
                ${bodyParams ? `data:bodyParams` : ''}
               }`
        : ''}
        );
      }
     `;
  }
}
````

## 生成的代码截图
问题1:
没有初始化表达式，且未在构造函数中明确赋值
![image](https://user-images.githubusercontent.com/30042334/68110892-d04d1c80-ff28-11e9-85c9-a0758176adb5.png)
![image](https://user-images.githubusercontent.com/30042334/68110904-d6db9400-ff28-11e9-9cd5-aae6b6947ad4.png)

问题2:
2.类型“XX”不是泛型类型
![image](https://user-images.githubusercontent.com/30042334/68111004-14402180-ff29-11e9-87d6-973e38742354.png)
![image](https://user-images.githubusercontent.com/30042334/68111013-199d6c00-ff29-11e9-833e-36eecf25d0dd.png)
**Detail**
![image](https://user-images.githubusercontent.com/30042334/68111028-24f09780-ff29-11e9-8106-6f32a38db4d8.png)

## 想要解决的问题
1. 问题1的这种报错能不能通过设置来避免，还是只能通用禁用tslint 规则
2. 问题2 要怎么解决，是swagger 的问题，还是哪里需要配置

**Comment by linningmii** [comment]
1. 问题1是tsconfig导致的，目前推荐做法是ignore掉对应的生成目录
2. 问题2需要提供一下swagger的api-docs

**Comment by LbhFront-end** [comment]
> 1. 问题1是tsconfig导致的，目前推荐做法是ignore掉对应的生成目录
> 2. 问题2需要提供一下swagger的api-docs


[api-doc.zip](https://github.com/alibaba/pont/files/3806658/api-doc.zip)
请问是这个东西吗？

**Comment by jasonHzq** [comment]
看下文档，在 tsconfig 里把 api.d.ts 配置到 includes 里

**Comment by hjtgzh** [comment]
> 看下文档，在 tsconfig 里把 api.d.ts 配置到 includes 里

第一个问题呢？
