### ISSUE TITLE
pont engine 命令行更新Mod和Bo命令无效

### ISSUE THREAD

**Issue by duibu05** [alibaba/pont#119]
## What happens(发生了什么)?
pont updateMod、pont updateBo无效

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):**
1. 修改swagger.json，pont diff检查更新
2. 运行pont updateMod modName或者pont updateBo boName
3. 或者运行pont updateMod modName && pont generate或者pont updateBo boName && pont generate

**Expected behavior(预期行为)**
预期更新指定的模块或者基类代码，实际什么都没有发生

**Thinking&Try(思考及尝试)**
1. pont update运行后未持久化更新lock文件，也没有regenerate files
2. 在源码cmd.ts的updateBo和updateMod的action里调用manager.regenerateFiles即可解决update不生效问题(见图片)

![671428C5-1F04-4DD9-AA35-3417C26560DD](https://user-images.githubusercontent.com/10591960/68189388-203de900-ffe6-11e9-8f38-aeba9076a58e.png)

## Context(上下文)
- **pont Version**: pont-engine 0.3.4
- **Node Version**: v10.16.3
- **Platform(操作系统平台)**: OSX 10.13.1

**Comment by duibu05** [comment]
追加：
pont generate只有第一次能生成全量代码，之后如果swagger.json发生变化后只运行pont generate本地代码不会有任何变动，并没有重新生成

**Comment by 521huaihuai** [comment]
一样遇见过....

**Comment by jasonHzq** [comment]
请阅读文档，pont generate 只是根据本地数据源生成代码，如果要更新，请使用 pont sync、pont updateAll 等。另外建议使用 vscode-pont 插件。
