### ISSUE TITLE
又爱又恨, 可以直接跳过写接口, 但是切换网络时,pont请求不通时会直接导致vsCode卡的没有提示功能了,

### ISSUE THREAD

**Issue by 521huaihuai** [alibaba/pont#120]
## Background(背景)

对问题的清晰而简明的描述。我总是很遗憾当…

## Proposal(建议)

Describe the solution you'd like, better to provide some pseudo code.
描述您想要的解决方案，最好提供一些伪代码。

## Additional context(附加上下文)

在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by jasonHzq** [comment]
嗯，离线情况不应该影响插件体验，需要看一下

**Comment by jasonHzq** [comment]
亲试在离线情况下体验了 pont，使用流畅，没有发现异常。是不是你的其它插件导致的？
