### ISSUE TITLE
后端的类型不一致怎么设置?比如说int可以转换成number吗?

### ISSUE THREAD

**Issue by 540240126** [alibaba/pont#129]
## What happens(发生了什么)?
生成的文件里面有些类型是int，但是再ts里面只有number，而不是int类型

A clear and concise description of what the bug is(对错误的清晰而简明的描述).

## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.

**Expected behavior(预期行为)** 1. 2.

## Context(上下文)

- **pont Version**:
- **Node Version**:
- **Platform(操作系统平台)**:

**Comment by gaoletian** [comment]
> 生成的文件里面有些类型是int，但是再ts里面只有number，而不是int类型


这个并不是很大的痛点，ts目前还不支持 integer类型

**Comment by 540240126** [comment]
![image](https://user-images.githubusercontent.com/24424056/71153618-8750ed80-2274-11ea-8ece-2d1a1b4fe76b.png) 你可能没理解我的意思，类似这图中生成的文件内容里面出现了int，int不应该转换成number吗

**Comment by gaoletian** [comment]
@540240126 我们需要测试一下，pont内部处理了integer类型，确实没有处理int，我们需要讨论一下尽快修复这个问题
