### ISSUE TITLE
使用README中的transform生成api.d.ts报TS2694: Namespace 'defs.xxx' has no exported member 'yyyyy'.

### ISSUE THREAD

**Issue by crazyll** [alibaba/pont#132]
## What happens(发生了什么)?
使用README中的transform生成api.d.ts报TS2694: Namespace 'defs.xxx' has no exported member 'yyyyy'.

## A clear and concise description of what the bug is(对错误的清晰而简明的描述).
当遇到
```
{
    "type":"object",
    "properties":{
        "id":{
            "type":"integer",
            "format":"int64"
        },
        "user":{
            "originalRef":"UserDto",
            "$ref":"#/definitions/UserDto"
        },
    },
    "title":"Apply"
}
```
这种类型嵌套的情况 api.d.ts 会报 error TS2304: Cannot find name 'UserDto'.

改成
```
  // 获取所有typeName
  let typeNames = JSON.stringify(mods).match(/"typeName":".+?"/g);

  typeNames = Array.from(new Set(typeNames))
    .map(item => item.split(':')[1].replace(/\"/g, '')) // 去重

  // 从 baseClasses 中取typeName的值----增加的部分
  data.baseClasses.forEach(cls => {
    let types = JSON.stringify(cls).match(/"typeName":".+?"/g);
    types = Array.from(new Set(types)) // 去重
      .map(item => item.split(':')[1].replace(/\"/g, ''));
    const nameSet = new Set([...typeNames, ...types]);
    typeNames = Array.from(nameSet);
  });
```
之后再过滤baseClasses可以解决上面的问题。

**Comment by gaoletian** [comment]
/**
 * 过滤mod及所依赖的baseClass
 * @param filterMods Mod.name数组
 * @param data StandardDataSource
 */
function filterModsAndBaseClass(filterMods: string[], data: StandardDataSource) {
  // 过滤mod
  let mods = data.mods.filter(mod => filterMods.includes(mod.name));
  // 获取所有typeName
  let typeNames = getTypeNames(mods);

  // 过滤baseClasses
  let baseClasses = data.baseClasses.filter(cls => typeNames.includes(cls.name));
  // 收集baseClasses 内部嵌套的 baseClasse
  typeNames = getTypeNames(baseClasses);
  baseClasses = [...baseClasses, ...data.baseClasses.filter(cls => typeNames.includes(cls.name))];

  return { mods, baseClasses };
}

/**
 * 获取所有typeName
 * @param modsOrBaseClasses
 */
function getTypeNames(modsOrBaseClasses: Mod[] | BaseClass[]) {
  // 获取所有typeName
  let typeNames = JSON.stringify(modsOrBaseClasses).match(/"typeName":".+?"/g);
  typeNames = Array.from(new Set(typeNames)) // 去重
    // 取typeName的值
    .map(item => item.split(':')[1].replace(/\"/g, ''));
  return typeNames;
}
