### ISSUE TITLE
可以增加 .pont-config.js 配置么？

### ISSUE THREAD

**Issue by denglingbo** [alibaba/pont#134]
## Background(背景)
项目中的 prettierrc 可能来自团队的自定义配置，该配置在npm 包内

## Proposal(建议)
建议类似 .pretterrc.js .eslintrc.js 一样可以多支持一些配置

**Comment by jasonHzq** [comment]
1、pont-config.json 可以支持 prettier 配置。

2、你是希望用 js 配置文件替代 json 配置文件，生成动态配置吗？

**Comment by denglingbo** [comment]
> 1、pont-config.json 可以支持 prettier 配置。
> 
> 2、你是希望用 js 配置文件替代 json 配置文件，生成动态配置吗？

嗯嗯，是的

**Comment by jasonHzq** [comment]
已沟通。可以通过 prettierConfig 完成配置
