### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by denglingbo** [alibaba/pont#140]
## What happens(发生了什么)?

生成api成功，但是紧接着报错如下：
{ code: "eaddrinuse", errno: "eaddrinuse", syscall: "listen", "address": "::", port: 8080 }

## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

## How To Reproduce(如何重现)
因为后端 model 名存在中文，我添加了一层 node 去转换中文，半个月前都是ok的，这几天才出现这个bug，怀疑是 pont 版本更新导致

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.

**Expected behavior(预期行为)** 1. 2.

## Context(上下文)

- **pont Version**:
- **Node Version**:
- **Platform(操作系统平台)**:

**Comment by jasonHzq** [comment]
请依照 issue 要求，提供下你的上下文。包括：1、swagger 返回数据 2、你的 pont 配置
