### ISSUE TITLE
配置多swagger时，generate出现命名空间丢失的情况

### ISSUE THREAD

**Issue by twobin** [alibaba/pont#141]
## What happens(发生了什么)?

pont-config 配置了 dass/featurePlatform/autodom 三份 swagger，如果只 generate 其中一个环境时，会出现命名空间丢失的情况，再 generate 其他环境后命名空间正常。

## Mini Showcase Repository(迷你展示库)

团队内部，op-daas 项目可以重现，请至团队内部查找对应的项目地址

## How To Reproduce(如何重现)

1、vscode 打开项目代码，初始化生成 pont 接口代码；
2、sync 后 generate daas 接口代码；
3、daas mod 中出现了丢失以 daas 为命名空间的情况；
4、切换 origin 为 featurePlatform，generate featurePlatform 接口代码后命名空间正常；

## Context(上下文)

![image](https://user-images.githubusercontent.com/3983192/74657971-4c176000-51cc-11ea-85cf-4cbcd3e85e04.png)

![image](https://user-images.githubusercontent.com/3983192/74657930-3a35bd00-51cc-11ea-8d5e-0975ce9891c6.png)

**Comment by jasonHzq** [comment]
generate 应是只生成当前数据源的代码。

**Comment by Leon1Zhu** [comment]
3.2版本问题，新版本中已修复，更新版本即可
