### ISSUE TITLE
Cannot find module 'inquirer'

### ISSUE THREAD

**Issue by Fiv5** [alibaba/pont#149]
## What happens(发生了什么)?
Cannot find module 'inquirer'

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.
1. install -g pont-engine
2. pont start

**Expected behavior(预期行为)** 1. 2.
start success

## Context(上下文)

- **pont Version**: 0.3.11
- **Node Version**: v8.12
- **Platform(操作系统平台)**: MAC OS

**Comment by Leon1Zhu** [comment]
新版本中已经修正该错误
