### ISSUE TITLE
pont生成的mock不是预定的数值

### ISSUE THREAD

**Issue by jaysg** [alibaba/pont#157]
## What happens(发生了什么)?

![6E74826F-DF21-48fc-9350-90434CC29F68](https://user-images.githubusercontent.com/28700250/76843980-95180e00-6877-11ea-8c32-0404169519c8.png)

![6E74826F-DF21-48fc-9350-90434CC29F68](https://user-images.githubusercontent.com/28700250/76843968-8fbac380-6877-11ea-8dc4-a42634fe3f1a.png)

1.如何可以让生成的mock是对应的枚举值
2.int能够生成整形的数值
3.日期型数值为时间戳
求解

- **pont Version*0.3.x*:
- **Node Version*10.15*:
- **Platform(操作系统平台)*win10*:

**Comment by ckken** [comment]
同问

**Comment by jasonHzq** [comment]
pont 只是生成默认的 mocks 值，这个文件用户是可以自己修改自定义的。

关于自动生成默认 mocks 值的准确性，我们会进一步优化
