### ISSUE TITLE
mock的wrapper配置不生效

### ISSUE THREAD

**Issue by henryzp** [alibaba/pont#158]
## What happens(发生了什么)?

mock的wrapper配置不生效

## How To Reproduce(如何重现)

1. 配置了`pont-config.json`: 

```json
{
    "mocks": {
          "enable": true,
          "port": 8111,
          "wrapper": "{\"code\": 0, \"data\": {response}, \"message\": \"\"}"
   }
}
```

2. vscode编辑器划过某个方法，右键打开 visit mocks interface，会在浏览器上打开一个tab，该tab的返回内容并没有`wrapper`里面的`code`等内容（而且打开的时候默认是8080，而我配的是8111，当然8111的也可以打开）

## Context(上下文)

- **pont Version**: 0.3.14
- **Node Version**:  v10.17.0
- **Platform(操作系统平台)**: mac

**Comment by Jack-rainbow** [comment]
同上，mock状态下wrapper不生效.

**Comment by henryzp** [comment]
@Jack-rainbow ，我加了钉钉群，问了一下，好像把vscode的那个插件升级一下就行了。。

**Comment by Jack-rainbow** [comment]
![image](https://user-images.githubusercontent.com/20368037/77273993-d5e8aa80-6cef-11ea-9333-70c53c0a084c.png)
我想请问下，你成功了吗？我是0.3.20

**Comment by henryzp** [comment]
@Jack-rainbow 是的，0.3.20版本是可以的。。我测试了。

你要是不行的话，重启一下vscode，应该是ok的。在pont-config.json里面需要手动配置一下mock的wrapper
