### ISSUE TITLE
有考虑提供umi的插件，和umi结合起来使用吗？

### ISSUE THREAD

**Issue by huyansheng3** [alibaba/pont#162]
## Background(背景)

对问题的清晰而简明的描述。我总是很遗憾当…

## Proposal(建议)

Describe the solution you'd like, better to provide some pseudo code.
描述您想要的解决方案，最好提供一些伪代码。

## Additional context(附加上下文)

在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by Leon1Zhu** [comment]
目前没有支持计划，如果有好的想法，我们非常欢迎大家提交PR
