### ISSUE TITLE
api名出现如 /enum 的话 会报错

### ISSUE THREAD

**Issue by ckken** [alibaba/pont#165]
## What happens(发生了什么)?

A clear and concise description of what the bug is(对错误的清晰而简明的描述).

## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.

**Expected behavior(预期行为)** 1. 2.

## Context(上下文)

- **pont Version**:
- **Node Version**:
- **Platform(操作系统平台)**:

**Comment by ckken** [comment]
生成列表 不会做 泛型 约束  api.d.ts
```
//理想情况
export type Response = defs.PaginationResultObject<defs.SysUserQueryVoObject>
//
实际情况
export type Response = defs.SysUserQueryVoObject
```

**Comment by Leon1Zhu** [comment]
可以提供下接口文档吗

**Comment by ckken** [comment]
暂时不方便提供 因为涉及到公司业务内容 目前是 删除敏感字来过滤

**Comment by jasonHzq** [comment]
> 暂时不方便提供 因为涉及到公司业务内容 目前是 删除敏感字来过滤

那可以创造一个实际例子吗？否则无法为你排查，或者你也可以 clone pont 源码进行排查。
