### ISSUE TITLE
Error: Error: Cannot find module './scripts'

### ISSUE THREAD

**Issue by iamsjh** [alibaba/pont#169]
执行 pont ls 或者 start，会报一个Error: Error: Cannot find module './scripts'
调用栈：
at Object.getTemplate  /pont-engine/lib/utils.js:326:19
at Manager.setFilesManager  pont-engine/lib/manage.js:332:82
at Manager.getGeneratedFiles

**Comment by Leon1Zhu** [comment]
本地未复现，猜测是环境问题？
