### ISSUE TITLE
生成的代码中未包含pontCore

### ISSUE THREAD

**Issue by strange-fish** [alibaba/pont#170]
## What happens(发生了什么)?
生成的代码中未包含pontCore
A clear and concise description of what the bug is(对错误的清晰而简明的描述).
按照教程步骤走了一遍，生成的代码中未包含pontCore
## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.

**Expected behavior(预期行为)** 1. 2.

## Context(上下文)
pont-config.json
```json
{
  "originType": "SwaggerV2 | SwaggerV3",
  "originUrl": "",
  "name": "service",
  "outDir": "./src/services",
  "fetchMethodPath": "./src/fetch",
  "templatePath": "./pontTemplate",
  "surrounding": "javaScript",
  "mocks": {
    "enable": false
  },
  "templateType": "fetch"
}
```

- **pont Version**:  1.0.3
- **Node Version**:  v12.13.0
- **Platform(操作系统平台)**: OS X

**Comment by strange-fish** [comment]
手动配置缺少surrounding会导致不生成pontCore.js

**Comment by crimson968** [comment]
> 手动配置缺少surrounding会导致不生成pontCore.js

请问这个问题是怎么解决的呢，我配置了surrounding也没有生成pontCore。
