### ISSUE TITLE
在pont-config.json中配置了两个swagger源，并配置mocks.enable为true，但是生成的mocks文件夹中只有一个源的mock数据

### ISSUE THREAD

**Issue by SunshineH2** [alibaba/pont#171]
## What happens(发生了什么)?
在pont-config.json中配置了两个swagger源，并配置mocks.enable为true，但是生成的mocks文件夹中只有一个源的mock数据

## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.
在pont-config.json中配置了两个swagger源，
![image](https://user-images.githubusercontent.com/31178307/80296578-13d56480-87af-11ea-9458-712aee5db7c2.png)
设置mocks.enable为true
在生成的.mocks文件夹中只存在一个mocks.ts文件，只生成了一个源的mock数据
**Expected behavior(预期行为)** 1. 2. 
在.mocks文件夹中能生成两个源的mock数据

## Context(上下文)

- **pont Version**: 1.0.3
- **Node Version**:
- **Platform(操作系统平台)**: windows 10

**Comment by jasonHzq** [comment]
切换两个数据源，都点击一次生成代码。

**Comment by SunshineH2** [comment]
> 切换两个数据源，都点击一次生成代码。

大佬能否说的明白些？我切换了数据源，但是mocks文件并没有变化，还是只有一个数据源的

**Comment by z979054461** [comment]
目前只支持生成当前选中数据源的mock数据。可以切换数据源，然后使用快捷键ctrl+command+M刷新数据。
