### ISSUE TITLE
[请教] dip 接口文档平台在 GitHub, Gitee, 搜索引擎怎么都搜不到，请问能给个链接吗？

### ISSUE THREAD

**Issue by TommyLemon** [alibaba/pont#172]
![image](https://user-images.githubusercontent.com/5738175/80724454-71add780-8b34-11ea-8d90-62b399c3c9f3.png)

![image](https://user-images.githubusercontent.com/5738175/80724545-8e4a0f80-8b34-11ea-8ebf-91d9de75c43d.png)

![image](https://user-images.githubusercontent.com/5738175/80724624-a752c080-8b34-11ea-9fcd-8567eab8f308.png)

![image](https://user-images.githubusercontent.com/5738175/80724827-dec16d00-8b34-11ea-80b3-948de22058fc.png)

![image](https://user-images.githubusercontent.com/5738175/80724704-bb96bd80-8b34-11ea-938c-ab5430e8cf10.png)

![image](https://user-images.githubusercontent.com/5738175/80724756-c94c4300-8b34-11ea-9fd3-9cea8e7df881.png)

PS：目前 VPN 用不了，不能 Google

**Comment by TommyLemon** [comment]
Google 了也没找到 HTTP 接口相关，包含 dip 关键词的项目或软件，都只有硬件上的 dip 接口

**Comment by z979054461** [comment]
没懂你要找的“dip 接口文档平台”是什么，可以具体一些吗？

**Comment by z979054461** [comment]
关闭长时间不活跃issue
