### ISSUE TITLE
mocks不知道怎么操作

### ISSUE THREAD

**Issue by xbcc123** [alibaba/pont#176]
## What happens(发生了什么)?
mocks怎么使用，怎么验证？

A clear and concise description of what the bug is(对错误的清晰而简明的描述).
我现在使用vs code编辑器，安装了pont 插件版本为1.0.3， pont-config.json 中mock已配置，使用浏览器打开 http://localhost:8080/ 没有服务？

## Mini Showcase Repository(迷你展示库)
```
{
  "originUrl": "https://petstore.swagger.io/v2/swagger.json",
  "templatePath": "./pontTemplate",
  "outDir": "./services",
  "surrounding": "javaScript",
  "mocks": {
    "enable": true
  },
  "templateType": "fetch"
}
```

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.
pont start 生成配置 mock选择true

**Expected behavior(预期行为)** 1. 2.
浏览器可以打开 http://localhost:8080

## Context(上下文)

- **pont Version**:  1.0.3
- **Node Version**: v12.16.2
- **Platform(操作系统平台)**: windows10

**Comment by jasonHzq** [comment]
建议你本地做如下检查，进一步排查原因：

1、检查本地有无生成 .mocks 文件夹。
2、检查 8080 端口是否与你本地端口号冲突，如果冲突，改变 mocks.port 配置。
3、检查 IDE 开发者工具中，Console 是否报错。
4、在 IDE 中，右键具体接口代码，访问完整的接口地址。

**Comment by cycle263** [comment]
@jasonHzq mock支持https么？

**Comment by crimson968** [comment]
遇到了同样的问题，请问解决了吗

**Comment by z979054461** [comment]
@xbcc123  @crimson968 
补充：
1、根目录创建一个.gitignore文件
2、墙裂建议换个port
```js
  "mocks": {
    "enable": true,
    "basePath": "",
    "port": 8080,
    "wrapper": "{\"code\": 0, \"data\": {response}, \"message\": \"\"}"
  }
```
3、如果还有问题，打开OUTPUT-Log（Window），查看日志
![image](https://user-images.githubusercontent.com/42641779/141974536-0ddbd902-0e4b-4ab3-8b86-951fc243ad16.png)

**Comment by z979054461** [comment]
> @jasonHzq mock支持https么？

暂不支持，内部使用node http模块实现
