### ISSUE TITLE
visit mocks interface 无响应

### ISSUE THREAD

**Issue by wanzj-zy** [alibaba/pont#177]
## What happens(发生了什么)?

已经生成了mock数据，在页面代码部分中右键visit mocks interface选项，无任何响应。右键jump to mock position可以跳转。

- **pont Version**:1.0.3
- **Node Version**:12.16.3
- **Platform(操作系统平台)**:win10

**Comment by z979054461** [comment]
大概率是mock服务没有启动，可以打开OUTPUT-Log（Window）查看日志。
正常情况下右键选择visit mocks interface，会打开浏览器访问对应接口地址
![image](https://user-images.githubusercontent.com/42641779/142963356-11d0f020-cb2a-4cf3-8004-7edf0997da1e.png)
