### ISSUE TITLE
pont-engine的diff属性更新文案不正确

### ISSUE THREAD

**Issue by gepiK** [alibaba/pont#178]
## What happens(发生了什么)?
swagger doc更新，pont进行diff的结果中对于基类属性更新的描述不正确，
现在展示的结果是 "基类 <基类名称> 的属性 <基类名称> 已更新"
相关代码如下
https://github.com/alibaba/pont/blob/master/packages/pont-engine/src/diff.ts#L114

希望展示的 "基类 <基类名称> 的属性 <propName> 已更新"

**Comment by jasonHzq** [comment]
PR welcome
