### ISSUE TITLE
swagger2 部分api接口对象，导致读取远程数据接口失败

### ISSUE THREAD

**Issue by DaskV** [alibaba/pont#181]
## What happens(发生了什么)?

swagger2部分api地址对象，导致读取远程地址失败

## Mini Showcase Repository(迷你展示库)

报错内容：

Error: 读取远程接口数据失败！Error: compiler error in defname: Result«橱窗（新鲜好物）对象»

## How To Reproduce(如何重现)

发生错误的的swagger地址：   http://www.zykj007.com/shopping-client/v2/api-docs

**Expected behavior(预期行为)** 1. 2.

## Context(上下文)

- **pont Version**: 1.0.3
- **Node Version**:10.15.2
- **Platform(操作系统平台)**: windows10

**Comment by z979054461** [comment]
你可以把这个基类（“橱窗（新鲜好物）对象”）的名称改一下，目前是按照以下这个正则自动翻译中文基类的，没有匹配中文括号
/"[a-z0-9\s-]*[\u4e00-\u9fa5]+[a-z0-9\s-«»()\u4e00-\u9fa5]*":/gi
