### ISSUE TITLE
open api v3 好像不支持

### ISSUE THREAD

**Issue by mushan0x0** [alibaba/pont#183]
我的配置：

```json
{
  "originUrl": "http://mock.trafficpro.alpha.lyd.parsec.com.cn/openapi.json",
  "templatePath": "./pontTemplate",
  "outDir": "./services",
  "surrounding": "javaScript",
  "mocks": {
    "enable": true
  },
  "templateType": "hooks"
}
```

生成的内容：

![image](https://user-images.githubusercontent.com/29084441/88909977-5b77fa80-d28e-11ea-9843-12e5cac9c5d4.png)

**Comment by z979054461** [comment]
你的originUrl链接打不开，指的是swagger版本吗？
配置中增加`"originType": "SwaggerV3",`（如果不生效，使用`origins`来配置源类型）
[单数据源的情况下设置originType失败 #244](https://github.com/alibaba/pont/issues/244#issue-972255975)
