### ISSUE TITLE
pont同步过程被打断之后，以后启动项目都会报错的解决办法

### ISSUE THREAD

**Issue by qqack** [alibaba/pont#185]
## What happens(发生了什么)?

在pont同步的时候，电脑突然关机，导致pont同步失败。之后再打开项目，pont会报以下错误：
![image](https://user-images.githubusercontent.com/11495559/90117669-d0b4f680-dd89-11ea-9bcf-ddfbb7aca661.png)

## 如何解决
windows系统下，删除C:/Users/xxx/.pont文件夹；
Mac系统，删除~/.pont文件夹；

然后重新打开vscode，pont会自动重新开始同步，然后就可以了。

**Comment by dogrod** [comment]
mac 出现相同表现，不过不知道是什么导致的。删除 ~/.pont 后可以了，谢谢
