### ISSUE TITLE
点击sync时，出现cannot read property 'mods' of undefined

### ISSUE THREAD

**Issue by huangup** [alibaba/pont#190]
![image](https://user-images.githubusercontent.com/13741256/90842900-fac27600-e392-11ea-9b75-559d1fab813f.png)

![image](https://user-images.githubusercontent.com/13741256/90842839-d1a1e580-e392-11ea-9bd0-9f33a7c9db6d.png)

**Comment by clydeqin7** [comment]
@huangup https://github.com/alibaba/pont/issues/185#issue-678291514 试试这个，我跟你一样的报错，亲测有效

**Comment by huangup** [comment]
> @huangup [#185 (comment)](https://github.com/alibaba/pont/issues/185#issue-678291514) 试试这个，我跟你一样的报错，亲测有效

感谢
