### ISSUE TITLE
能否配置api名称的生成规则?

### ISSUE THREAD

**Issue by weiming8202** [alibaba/pont#201]
能否配置api名称的生成规则?

**Comment by weiming8202** [comment]
![123456789](https://user-images.githubusercontent.com/1166440/97078555-853b8600-161f-11eb-9779-b05c8bd373bf.jpg)
![1234567890000](https://user-images.githubusercontent.com/1166440/97078560-8a98d080-161f-11eb-9967-c06edd546aeb.jpg)

url:/api/v5/projects/get 生成出了getGet的api名称；
url:/api/v5/projects/admin/get 生成出了get的api名称；

如何才能生成出带有类似getForAdmin之类的api名称呢？

**Comment by weiming8202** [comment]
请问，是否不能用get作为url最后的名称？跟代码生成器的保留字符有关吗？

**Comment by jasonHzq** [comment]
pont 是默认开启 usingOperationId 的，你是不是自己关掉了

**Comment by ianfuin** [comment]
可以通过 transformPath 来修改 StandardDataSource 中的 name
