### ISSUE TITLE
当restful api的path中有匹配时，生成的前端代码无法满足需求

### ISSUE THREAD

**Issue by quicklearning123** [alibaba/pont#203]
## Background(背景)

当后端的controller注解是@DeleteMapping("/delete/{id}")，生成的前端代码为，PontCore.getUrl('/delete/{id}')

前端现有的代码是：
```
export async function deleteMember(id: number) {
    return request(`/delete/${id}`, {});
}
```
怎么兼容这种情况呢？

**Comment by Go7hic** [comment]
这个问题 官方没有回复么？ 应该是没考虑到这个情况  需要自己去修改模板

**Comment by JayCJP** [comment]
这种情况可以自己修改 生成的代码片段
