### ISSUE TITLE
refresh mocks data 失败

### ISSUE THREAD

**Issue by chengxuan12** [alibaba/pont#204]
vscode 执行 refresh mocks data 失败。

然后查看 vscode-pont/src/mocks.ts 源码文件的 refreshMocksCode 方法。

    const rootPath = vscode.workspace.rootPath;
    const mockPath = path.join(rootPath, '.mocks/mocks.ts');
    const code = this.getMocksCode();
    if (!fs.existsSync(path.join(rootPath, '.mocks'))) {
      fs.mkdirSync(path.join(rootPath, '.mocks'));
    } else {
      fs.unlinkSync(path.join(rootPath, '.mocks'));
      fs.mkdirSync(path.join(rootPath, '.mocks'));
    }
    await fs.writeFile(mockPath, code);

fs.unlinkSync(path.join(rootPath, '.mocks'));  使用上有疑问，为什么执行这段代码。即使想删除，unlinkSync 只删除文件，应该是无法删除 .mocks 文件夹。

**Comment by z979054461** [comment]
![image](https://user-images.githubusercontent.com/42641779/141785358-a7c7f977-ccef-4f9d-b36c-889c53e1c338.png)
复现步骤：使用快捷键，在OUTPUT栏-Log（Window）中可以看到报错
