### ISSUE TITLE
生成的接口类型的request函数提示无法导出

### ISSUE THREAD

**Issue by noel-blazblue** [alibaba/pont#208]
想访问到这个函数的类型：
![image](https://user-images.githubusercontent.com/47893069/102957867-881b0000-4516-11eb-96fc-e0c334d312b9.png)

结果提示：
![image](https://user-images.githubusercontent.com/47893069/102957918-a5e86500-4516-11eb-9608-977da6ee0dd0.png)

期待结果：
能在自己的请求方法中使用调出的request接口类型。

**Comment by jasonHzq** [comment]
typeof API.[mod].[interface].[request]
