### ISSUE TITLE
 responses 中没有 $ref 不会生成返回值类型

### ISSUE THREAD

**Issue by lifegit** [alibaba/pont#216]
## Background(背景)

因swagger文件是Yapi导出， responses 中没有 $ref ，这样会导致生成的 baseClass 文件中没有任何返回值的类型。是否考虑图2情况下，没有$ref时，直接解析 properties。

## Proposal(建议)
1. 没有$ref时，直接解析 properties。 
2. 在生成Pont元数据前，允许添加函数中间件，让开发者自己处理（transformPath 的文件中）

## Additional context(附加上下文)
![image](https://user-images.githubusercontent.com/33006878/108958886-915b5100-76ae-11eb-8583-174b49507b1e.png)
![image](https://user-images.githubusercontent.com/33006878/108959253-1e9ea580-76af-11eb-8fd2-aadbf57c13fe.png)

**Comment by lifegit** [comment]
swagger 文件

https://app.swaggerhub.com/apiproxy/registry/t4943/t22/last

**Comment by longyuanJason** [comment]
我司也是用的yapi，发现有一样的问题，请问下后来有什么好的解决方案吗
