### ISSUE TITLE
多数据源下出现的关于pontCore生成及引用、api.d.ts报错问题

### ISSUE THREAD

**Issue by mango-zhang** [alibaba/pont#218]
## What happens(发生了什么)?

- ts环境没有生成pontCore.ts文件

- js环境多数据源模式下api文件引入pontCore位置错误
- 多数据源模式下各个数据源生成文件夹下api.d.ts报错
A clear and concise description of what the bug is(对错误的清晰而简明的描述).
- ts环境没有生成pontCore.ts文件
- 多数据源 js环境模式下，有生成pontCore，但api文件引入pontCore位置错误；
- 多数据源模式下各个数据源生成文件夹下api.d.ts报错，具体报错信息如下：
    > - 命名空间“defs.catenary”没有已导出的成员“ObjectMap”   
    > - 此处也声明了 "ObjectMap"。
- api文件报错
    > - 属性未初始化

![1](https://user-images.githubusercontent.com/22792713/110587669-dbfcc300-81ae-11eb-9434-c4ff54913561.png)
![image](https://user-images.githubusercontent.com/22792713/110587834-1bc3aa80-81af-11eb-81fc-7fe6e7b3729f.png)
![2](https://user-images.githubusercontent.com/22792713/110587673-ddc68680-81ae-11eb-8c91-0ec82c166152.png)
![image](https://user-images.githubusercontent.com/22792713/110588762-76a9d180-81b0-11eb-9a64-e3ab532d4cd4.png)

## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).
```json
{
  "origins":[
    {
      "originUrl": "http://192.168.1.95:50006/v2/api-docs?group=catenary",
      "name":"catenary"
    },
    {
      "originUrl": "http://192.168.1.95:50006/v2/api-docs?group=drawing",
      "name":"drawing"
    } 
  ],
  "mocks": {
    "enable": true
  },
  "surrounding":"typeScript",
  "usingMultipleOrigins":true
}
```
```json
{
  "origins":[
    {
      "originUrl": "http://192.168.1.95:50006/v2/api-docs?group=catenary",
      "name":"catenary"
    },
    {
      "originUrl": "http://192.168.1.95:50006/v2/api-docs?group=drawing",
      "name":"drawing"
    } 
  ],
  "mocks": {
    "enable": true
  },
  "surrounding":"javaScript",
  "usingMultipleOrigins":true
}
```

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.

**Expected behavior(预期行为)** 1. 2.

## Context(上下文)

- **pont Version :1.0.13
- **Node Version**:12.16.1
- **Platform(操作系统平台)**:win10

**Comment by wanlijun** [comment]
为什么关闭了，我也出现了js环境多数据源模式下api文件引入pontCore位置错误，而且搜索出来接口路径不是完整的，请问怎么解决的呢

**Comment by balabalapupu** [comment]
我也复现了，同没解决，但是问题却关闭了....
