### ISSUE TITLE
在自动生成的时候提示Error: 读取远程接口数据失败！SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by cl510804194** [alibaba/pont#221]
后端的swagger文档可以正常访问，但是在某个swagger文档中提示了Error: 读取远程接口数据失败！SyntaxError: Unexpected token < in JSON at position 0，一直找不到原因，希望各位大佬是否有解决的方法

**Comment by yzStrive** [comment]
试试删除pont的缓存文件夹
```shell
rm -rf ~/.pont
```

**Comment by yzStrive** [comment]
> 后端的swagger文档可以正常访问，但是在某个swagger文档中提示了Error: 读取远程接口数据失败！SyntaxError: Unexpected token < in JSON at position 0，一直找不到原因，希望各位大佬是否有解决的方法

试试删除pont的缓存文件夹

```shell
rm -rf ~/.pont
```

**Comment by vndmea** [comment]
异常原因是个人目录下的 .pont 文件夹下的内容解析异常，删除后再重新生成即可

**Comment by xartd** [comment]
swagger 看下是否需要登录认证，不免登的话也是这个错误

**Comment by YardWill** [comment]
有没有手动加cookie的入口

**Comment by jasonHzq** [comment]
需要后端配置一下免登。否则的话插件直接访问是会报这个错的。

如果后端那边不好配合。你也可以直接访问 /v2/api-docs.json 把 Swagger 下载下来。然后开 http-server ，配置本地地址。
