### ISSUE TITLE
请求添加 WebStorm 支持 或者完善命令行相关命令

### ISSUE THREAD

**Issue by calldream** [alibaba/pont#234]
如题，希望主创团队添加 webStrom 的插件支持，或者完善 pont-engine 的命令行命令**及其文档**。
目前我的电脑上安装全局安装pont-engine后，pont start 命令只会在本地目录生成配置项文件，不会请求swagger生成ts。

pont start 命令问题具体描述：
1. 空项目 运行 pont start 命令，生成 pont-config.json 文件（正常）
2. 再次运行 pont start 命令，报错 请求 swagger 失败
3. 以后再次请求 pont start 命令， “检测到已存在pont-config文件，继续生成将覆盖配置项，是否继续？”

请求地址使用的是 swagger官方的demo地址：  https://petstore.swagger.io/v2/swagger.json

经测试，本地安装pont-engine后出现同样上述问题。
使用vsCode-pont则不会出现bug。

###  期望
1. 添加webStorm 的插件支持
2. 完善pont-engine 的命令行命令，修复bug，
3. 完善npm pont-engine 的页面中关于命令行操作的描述部分

**Comment by jasonHzq** [comment]
PR welcome
