### ISSUE TITLE
单数据源的情况下设置originType失败

### ISSUE THREAD

**Issue by ousiri** [alibaba/pont#244]
## What happens(发生了什么)?

单数据源的情况下设置originType失败。多数据源情况正常
```json
// pont-config.json
{
  "originUrl": "http://localhost:3000/doc-json",
  "originType": "SwaggerV3"
}
```

原因是`utils.ts`文件的`class Config`经过编译，originType总是等于`SwaggerV2`

## Mini Showcase Repository(迷你展示库)

无

## How To Reproduce(如何重现)

按照描述操作即可

## Context(上下文)

- **pont Version**:1.0.13
- **Node Version**:v14.15.4
- **Platform(操作系统平台)**:MacOS

**Comment by jasonHzq** [comment]
可以提个 PR 吗
