### ISSUE TITLE
在pont-config.json中配置了两个swagger源,怎么设置两个templatePath？在orgins配置会报错Error: 读取 lock 文件错误！Error: EROFS: read-only file system, open './pontTemplate.ts'

### ISSUE THREAD

**Issue by dragonkuang** [alibaba/pont#253]
## What happens(发生了什么)?

在pont-config.json中配置了两个swagger源,怎么设置两个templatePath？在orgins配置会报错Error: 读取 lock 文件错误！Error: EROFS: read-only file system, open './pontTemplate.ts'

## Mini Showcase Repository(迷你展示库)

配置项： 
"origins": [{
    "outDir": "./services",
    "templatePath": "./pontTemplate",
    "name": "activity",
    "originUrl": "****"
  }, {
    "outDir": "./services",
    "templatePath": "./template",
    "name": "qingrenjie",
    "originUrl": "****"
  }],

## Context(上下文)

- **pont Version**:
- **Node Version**:
- **Platform(操作系统平台)**:

**Comment by jasonHzq** [comment]
templatePath  是公共配置项。只能有一个。不同源如果想生成不同风格的 SDK。只能在 template 里做判断了。
