### ISSUE TITLE
Unexpected token } in JSON at position 15490

### ISSUE THREAD

**Issue by lr-27** [alibaba/pont#257]
点击sync出现
![image](https://user-images.githubusercontent.com/68773804/140001336-27106bb5-6ed3-4015-af7f-7d4bceeed36f.png)

![image](https://user-images.githubusercontent.com/68773804/140001289-f7a3ec91-d077-4079-9bc6-afd464ec61ad.png)

**Comment by jasonHzq** [comment]
你的lock 文件被损坏了，不符合 JSON 格式。建议删除后重新生成。

**Comment by lr-27** [comment]
您说的是 api-lock.json这个文件么？   删除后没有什么效果   目前该问题只有在macOS上出现 同样的代码windows电脑点击sync命令没有问题，还请大神详细解答下

**Comment by lr-27** [comment]
![image](https://user-images.githubusercontent.com/68773804/141710406-0c8efb82-8801-4b9e-981e-79c43aa4f061.png)
