### ISSUE TITLE
【问题】想自定义生成的文件夹层级

### ISSUE THREAD

**Issue by xiexingen** [alibaba/pont#297]
## Background(背景)

对问题的清晰而简明的描述。我总是很遗憾当…
比如目前的层级
|services
|--mods
|----pet
|------addPet.ts
|------deletePet.ts

期望的层级
## Proposal(建议)
|services
|--mods
|----pet.ts  里面包含，addPet、deletePet这些方法

Describe the solution you'd like, better to provide some pseudo code.
描述您想要的解决方案，最好提供一些伪代码。

## Additional context(附加上下文)

在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by ianfuin** [comment]
你好，可以通过  templatePath 配置重写 FileStructures.getFileStructures 方法来实现，或者 使用 transformPath 来修改标准数据源接口来实现
