### ISSUE TITLE
VSCode 侧边栏未显示 Pont 的 icon

### ISSUE THREAD

**Issue by rich1e** [alibaba/pont#304]
## What happens(发生了什么)?

VSCode 侧边栏未显示 Pont 的 icon。

## How To Reproduce(如何重现)

通过 VSCode 插件管理工具安装 Pont。

## Context(上下文)

- **pont Version**: v1.2.0
- **Node Version**: v16.13.2
- **Platform(操作系统平台)**: macOS Catalina 10.15.7

![image](https://user-images.githubusercontent.com/29914689/162351644-37414b2b-0f02-4f38-b60e-958519d01182.png)

**Comment by ianfuin** [comment]
你好，需要把插件升级到 1.3.0
