### ISSUE TITLE
读取远程接口数据失败Error: compiler error in defname。但问题字符串能被正则匹配

### ISSUE THREAD

**Issue by HanSuhhi** [alibaba/pont#311]
## (发生了什么)?

命令行执行 pont generate 后报错，Error: 读取远程接口数据失败！Error: compiler error in defname: 申购单PurchaseApply

## 展示

文档中只有三处位置用到了“申购单PurchaseApply”，且其他接口也是相似的命名规则。之前其他接口同步都是正常的，今天同步新增的申购单接口时突然报错。
按照#181 中的正则来匹配的话，应该是能被匹配中的。

`    
"申购单purchaseApply": {
            "type": "object",
            "properties": {
                "applyLoginName": {
                    "type": "string",
                    "description": "申请人登录名"
                },
                ...
            }
            "title": "申购单purchaseApply"
        },
`

---
`
   "PurchaseVo": {
            "type": "object",
            "properties": {
                "processInstance": {
                    "$ref": "#/definitions/钉钉流程实例信息processInstance"
                },
                "purchaseApply": {
                    "$ref": "#/definitions/申购单purchaseApply"
                },
                "purchaseApplyDetailList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/采购申请明细purchaseApplyDetail"
                    }
                }
            },
            "title": "PurchaseVo"
        },
`

---
这是pont-config.json的相关配置
`
{
  "originUrl": "http://192.168.xxx.xxx:xxxxx/material-admin/v2/api-docs",
  "templatePath": "./pontTemplate",
  "outDir": "../src/services",
  "surrounding": "typeScript",
  "mocks": {
    "enable": true
  }
}
`

## 关于复现

如有必要，可将后端文档地址映射至公网进行问题排查

- **pont Version**: 1.2.0
- **Node Version**: v16.13.0
- **Platform(操作系统平台)**: MacOS

**Comment by HanSuhhi** [comment]
与后端沟通后将**申购单**改成**采购单**后，运行正常

**Comment by xiweixiong** [comment]
感觉新版本问题多，反正我是用回了1.0.13

**Comment by shuishuidelin** [comment]
改个字就好了？这什么鬼

**Comment by HanSuhhi** [comment]
> 

可能是翻译器的问题...不过赶项目也不细看了，先跑再说
