### ISSUE TITLE
swaggerV3下template文件里getInterfaceContent获取的inter.getBodyParamsCode()为空

### ISSUE THREAD

**Issue by wangyibinwangyi** [alibaba/pont#313]
## What happens(发生了什么)?

swaggerV3下template文件里getInterfaceContent获取的inter.getBodyParamsCode()为空
导致没有办法区分传参是params还是bodyParams

## Mini Showcase Repository(迷你展示库)
swagger地址如下
https://apidev.gkxxjs.com/v3/api-docs

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.
1.pont-config.json如下
```
{
  "origins": [
    {
      "originUrl": "https://apidev.gkxxjs.com/v3/api-docs",
      "originType": "SwaggerV3"
    }
  ],
  "templatePath": "./pontTemplate",
  "outDir": "./src/services"
}
```

2.pontTemplate文件片段
```
import { CodeGenerator, Interface } from "pont-engine";
export default class MyGenerator extends CodeGenerator {
  getInterfaceContent(inter: Interface) {
    return inter.getBodyParamsCode();
  }
}
```
**Expected behavior(预期行为)** 1. 2.

## Context(上下文)

- **pont Version**:1.3.1
- **Node Version**:16.14.2
- **Platform(操作系统平台)**:macOS

**Comment by Kerbores** [comment]
同样的问题,看了一下lock文件里面也没有body参数
