### ISSUE TITLE
[pont.createManager]:执行失败

### ISSUE THREAD

**Issue by soberlizy** [alibaba/pont#321]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/62385556/174936898-73135f64-aded-4df0-a06b-4cf8f9ab0288.png">
控制台输出 
[readLocalDataSource]:开始
读取本地数据中...
读取本地完成
文件生成器创建中...
文件生成器创建成功！
[readLocalDataSource]:结束
----------------------
[pont.createManager]:Unexpected token } in JSON at position 24472
mac上出现的 window还没有看到有这个情况

**Comment by sweetliu** [comment]
我也出现这个问题了，请问是啥原因？ @soberlizy
