### ISSUE TITLE
pont无法使用

### ISSUE THREAD

**Issue by 1320611670** [alibaba/pont#331]
## What happens(发生了什么)?

pnst获取失败
![image](https://user-images.githubusercontent.com/77874445/184059150-fae5d2b0-0101-4d22-9dc7-59702cd3adad.png)

- **pont Version**: 1.2.0  换过多个版本
- **Node Version**: v16.13.0
- **Platform(操作系统平台)**: win11

**Comment by z979054461** [comment]
建议检查一下api-lock.json   内容是否被修改过导致不是JSON格式？

**Comment by ianfuin** [comment]
1.5 版本已经修复该问题
