### ISSUE TITLE
tag name被翻译，导致整个模块名发生变化，导致使用时报错

### ISSUE THREAD

**Issue by codertony** [alibaba/pont#333]
## What happens(发生了什么)?
tag name被翻译，导致整个模块名发生变化，导致业务层使用时报错
A clear and concise description of what the bug is(对错误的清晰而简明的描述).
swagger：
tags: [
    {
      "name":"文件controller",
      "description":"Doc File Controller"
    },
]

pont  1.0版本，解析出来模块名称是：docFile
pont  1.3.3版本，解析出来模块名称是：filecontroller

原因是:  文件controller被翻译成了filecontroller，进而被直接用成了模块名称

有没有什么配置，不要走翻译。

- **pont Version: 1.3.3
- **Node Version:  14.17.3
- **Platform(操作系统平台): windows

**Comment by ianfuin** [comment]
如果步骤翻译后续逻辑会出错，生成的class也是不规范的带中文名称，建议swaager注释修改成英文
