### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by JayCJP** [alibaba/pont#334]
## What happens(发生了什么)?

```
yarn install 
....

error An unexpected error occurred: "https://registry.npm.alibaba-inc.com/@alife/dt-hooks/download/@alife/dt-hooks-0.1.0.tgz: connect ETIMEDOUT 103.52.199.227:443".
```
本地安装依赖是 无法下载这个库
https://registry.npm.alibaba-inc.com/@alife/dt-hooks/download/@alife/dt-hooks-0.1.0.tgz

## How To Reproduce(如何重现)

pont clone 到本地  npm install 安装依赖

希望能正常下载，请问该库是否已经删除 或者是私有的 公网无法下载？

## Context(上下文)

- **pont Version**: 1.3.3
- **Node Version**:  v14.17.1
- **Platform(操作系统平台)**: window 10

**Comment by ianfuin** [comment]
dt-hooks 是内网环境包，公网无法下载
