### ISSUE TITLE
同时启用`"usingMultipleOrigins": true`和`"spiltApiLock": true` - 新增数据源时会报文件不存在的异常

### ISSUE THREAD

**Issue by bluryar** [alibaba/pont#338]
## What happens(发生了什么)?

同时启用`"usingMultipleOrigins": true`和`"spiltApiLock": true,`， 当新增数据源的时候， 会报错：
```
[pont.createManager]:ENOENT: no such file or directory, open 'c:\Users\jinku\Downloads\pont-demo-master\src\services\pet2\api-lock.json'
```

https://github.com/alibaba/pont/blob/db28ee45ea26bf8de0381411c4280eec2ea4244f/packages/pont-engine/src/main/Manager.ts#L221

这里没有像上边判断根目录数据源一样判断文件存在与否，导致报错了，不知道是不是不应该同时启用这两个选项？

## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

https://github.com/bluryar/pont-reproduce

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 
1. 新增数据源：
```json
{
  "outDir": "./src/services",
  "templatePath": "./pontTemplate",
  "spiltApiLock": true,
  "usingMultipleOrigins": true,
  "origins": [
    {
      "name": "pet1",
      "originUrl": "https://petstore.swagger.io/v2/swagger.json",
      "originType": "SwaggerV2"
    },
    {  // 新增
      "name": "pet2",
      "originUrl": "https://petstore.swagger.io/v2/swagger.json",
      "originType": "SwaggerV2"
    }
  ]
}

```

**Expected behavior(预期行为)** 
1. 已生成内容不改动
3. 增量更新对应的api-lick.json

## Context(上下文)

- **pont Version**: 1.4.0
- **Node Version**: 16.15.0
- **Platform(操作系统平台)**: win 11 x86

**Comment by bluryar** [comment]
这里新增一个新建文件夹的脚本会不会好点？

**Comment by ianfuin** [comment]
https://github.com/alibaba/pont/pull/339  这个mr已解决该问题，等待合并后新版发布

**Comment by ianfuin** [comment]
1.5 版本已修复该问题
