### ISSUE TITLE
pont执行失败

### ISSUE THREAD

**Issue by Lruler** [alibaba/pont#340]
## What happens(发生了什么)?
pont初始化失败
不清楚什么原因， 就是突然打开项目文件后就报错了(之前未修改过任何与pont相关的文件)
![2E1663E7-E165-4A4B-852E-A7F3A5143E72](https://user-images.githubusercontent.com/75160088/197498715-bed73c66-9b42-47fd-aed4-e719d307bf3d.png)

+ pont Version: 1.4.0
+ Node Version: v16.14.0
+ Platform(操作系统平台): MacOS

**Comment by ianfuin** [comment]
使用命令行工具 rm -rf ~/.pont
