### ISSUE TITLE
pont start后报错Error: ENOENT: no such file or directory, open 'D:\soft\nvm\v12.14.0\node_modules\pont-engine\lib\package.json'

### ISSUE THREAD

**Issue by jQChou** [alibaba/pont#348]
## What happens(发生了什么)?
pont start的时候报错缺package.json
![image](https://user-images.githubusercontent.com/19767705/201614352-b6572b6a-fc25-4b6f-978f-43799bd41c3e.png)
手动添加package.json后报错commander.default undefined
![image](https://user-images.githubusercontent.com/19767705/201614087-cabe9e15-1905-4ae1-b314-0c3a74754d4b.png)

## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.

**Expected behavior(预期行为)** 1. 2.

## Context(上下文)

- **pont Version**: 1.5.3
- **Node Version**: v12.14.0
- **Platform(操作系统平台)**: windows11

**Comment by Po3aaa** [comment]
Have same question, **node version**: v14.17.1, platform: win10

**Comment by z979054461** [comment]
最新版v1.5.12已无此问题，请升级后尝试
