### ISSUE TITLE
获远程接口数据失败 Error: compiler error in defname: DataList«task_alert_contact的实体类»

### ISSUE THREAD

**Issue by jonsen-liu** [alibaba/pont#369]
## What happens(发生了什么)?

[OriginManage 任务管理中心API] 本地数据源更新中...
[OriginManage 任务管理中心API] [fetchMethod] 获远程数据中...
[OriginManage 任务管理中心API] [translate] 翻译接口数据中的非法字符
[OriginManage 任务管理中心API] 解析接口文本数据
[OriginManage 任务管理中心API] [transform2StandardDataSource] 将远程数据转化成 pont 标准数据模型
[OriginManage 任务管理中心API] 获远程接口数据失败 Error: compiler error in defname: DataList«task_alert_contact的实体类»
[OriginManage 任务管理中心API] 本地数据源更新完成

## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).

## How To Reproduce(如何重现)

**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.

**Expected behavior(预期行为)** 1. 2.

## Context(上下文)

- **pont Version**: 1.5.7
- **Node Version**:v16.17.0
- **Platform(操作系统平台)**:win

**Comment by xiweixiong** [comment]
英文+中文的类名翻译不了，导致编译失败，改为全英文或全中文即可，一般最好是后台的英文类名

**Comment by z979054461** [comment]
#373 升级到最新版尝试一下

**Comment by z979054461** [comment]
#373 升级到最新版尝试一下
