### ISSUE TITLE
vs-code插件没有自动启动mock服务

### ISSUE THREAD

**Issue by flashzhj** [alibaba/pont#392]
## What happens(发生了什么)?

mock服务没有自动启动
[CustomTemplate] base 初始化模板
[getTemplate template] d:\wuyin_edesk\web_apps\aiclass-comment\node_modules\.pont\template\default\pontTemplate
[CustomTemplate] base 初始化模板完成
[Manager] initFilesManager start
[Manager] 初始化 fileStructures
[Manager] 初始化 filesManager
[Manager] initFilesManager end
[OriginManage ] 创建完成
[OriginManage ] 初始化数据源
[OriginManage ] 获取本地数据源
[OriginManage ] 本地数据源更新中...
[OriginManage ] 初始化模板文件
[CustomTemplate]  初始化模板
[CustomTemplate]  初始化模板完成
[OriginManage ] [fetchMethod] 获远程数据中...
[OriginManage ] 初始化数据源完成
[OriginManage ] 更新 CodeGenerator dataSource
[OriginManage ] [translate] 翻译接口数据中的非法字符
[OriginManage ] 解析接口文本数据
[OriginManage ] [transform2StandardDataSource] 将远程数据转化成 pont 标准数据模型
[OriginManage ] [transformStandardDataSource] 二次加工标准数据模型
[OriginManage ] 对解析后的标准数据源进行校验 
[OriginManage ] 获远程接口数据完成
[OriginManage ] 本地数据源更新完成
[Manager] 切换数据源:
[PollingManage] stopPolling
[PollingManage] startPolling

![E8ED0134-F13F-4248-93ED-ABA9CE476AB2](https://github.com/alibaba/pont/assets/59557859/17ea5e18-799b-41bd-8734-8fdc762ade7d)

![image](https://github.com/alibaba/pont/assets/59557859/c5a6dac8-3d1e-4c77-9475-8655bab5f813)

## Context(上下文)

- **vscode-pont插件 Version**: 1.5.12
- **pont Version**: 1.5.12
- **Node Version**: 16.20.1
- **Platform(操作系统平台)**:win10

**Comment by flashzhj** [comment]
服务启动了，但是各个mock接口没有请求到，再排查一下原因

**Comment by luchanan** [comment]
![image](https://github.com/user-attachments/assets/bb3daa71-5833-49ee-b7fd-089fdea65b1c)
打不开，不知道什么，请求也没反应，端口是测试过没有占用
