### ISSUE TITLE
如何给单独请求添加headers

### ISSUE THREAD

**Issue by Fhasghrge** [alibaba/pont#399]
全局添加headers可以通过重写pont的方式完成；但目前部分接口请求需要添加headers，这种情况下如何传headers？

**Comment by z979054461** [comment]
如果是使用PontCore，request(params, options = {})，直接把headers传到options里，PontCore调用的fetch，参考https://developer.mozilla.org/zh-CN/docs/Web/API/fetch

如果是自定义的请求方法，需要自己修改模板实现（templatePath）
