### ISSUE TITLE
不支持swagger的response或者request body的required字段

### ISSUE THREAD

**Issue by loveholly** [alibaba/pont#42]
**swagger的描述信息**
![图片](https://user-images.githubusercontent.com/5133856/56352245-61fd7280-6201-11e9-9a7a-a89f612dab9f.png)

**pont生成的api-lock信息**
![图片](https://user-images.githubusercontent.com/5133856/56352326-95400180-6201-11e9-81c1-777a9adba729.png)

在swagger里面是有required字段的，但是最终生成的api-lock文件里面没有该字段

**预期结果：**
![图片](https://user-images.githubusercontent.com/5133856/56352482-eb14a980-6201-11e9-8bfb-2b7a411f9fbb.png)

**Comment by jasonHzq** [comment]
已修复

**Comment by birdycn** [comment]
> 已修复

我也遇到这个问题，swagger body里是required，但是生成的api是可选状态
