### ISSUE TITLE
请问和 swagger-codegen 有何区别？

### ISSUE THREAD

**Issue by luv-sic** [alibaba/pont#43]
https://github.com/swagger-api/swagger-codegen

**Comment by gaoletian** [comment]
pont 对于前端开发来说更加友好，可定制化更高，你可以按照自己的需要来定制，另外 pont 提供了 pont-vscode 插件，使用起来是非常方便的。还有很多贴心功能，比如快速同步接口变更等等

**Comment by gaoletian** [comment]
pont 对于前端开发来说更加友好，可定制化更高，你可以按照自己的需要来定制，另外 pont 提供了 pont-vscode 插件，使用起来是非常方便的。还有很多贴心功能，比如快速同步接口变更等等
