### ISSUE TITLE
部分body参数的类型会丢失

### ISSUE THREAD

**Issue by loveholly** [alibaba/pont#44]
**swagger** 描述
![图片](https://user-images.githubusercontent.com/5133856/56403253-04196b00-6293-11e9-8a7b-30082477cf57.png)

**生成的api-lock描述**
![图片](https://user-images.githubusercontent.com/5133856/56403280-2317fd00-6293-11e9-9ce3-769b5f08ac1d.png)

swagger里面的body标注了参数类型为`Array<string>`，但是生成之后却没有类型信息了

**Comment by jasonHzq** [comment]
建议加钉钉群聚焦反馈一下。定位好问题，我们再更新issue。

**Comment by jasonHzq** [comment]
已复现。目前 body params 都当成某个基类来处理，没有考虑到普通类型。尽快修复

**Comment by loveholly** [comment]
这个我来修复吧
