### ISSUE TITLE
Pont Contributor 招募

### ISSUE THREAD

**Issue by jasonHzq** [alibaba/pont#45]
# Pont Contributor 招募

Pont 开源后，使用的项目越来越多。然而现有 Contributor 业余时间有限，Pont 维护，Roadmap 推进也难以为继。

如果你认同 Pont 的价值，欢迎成为 Pont Contributor 的一员。你可以挑选感兴趣的技术点，一起推进 Pont Roadmap。让 Pont 能够在更多项目中放大价值，大放异彩，让我们在开源建设中一起成长。

#### Pont Contributor 小组运作规则

* 模块分工，负责人不重复；

* 任何 PR 需要 Code Review 才能合并；

* 功能变动及设计需要 Contributor 小组达成一致；新功能必须新增单测。

有兴趣可以添加 Pont 钉钉交流群联系我。

**Comment by jackson-yyy** [comment]
还能加吗，钉钉搜索不到
