### ISSUE TITLE
Pont安装不成功

### ISSUE THREAD

**Issue by at77ms** [alibaba/pont#46]
在 vsCode1.30和1.33版本上都试过(.zip解压版，用户无系统管理员权限，win7 64位英文版系统)。
附件为手动下载了 jasonHzq.vscode-pont-0.1.61.vsix之后安装报错的提示文件。

[VSIXInstaller_7f9618c5-ad6e-47ff-8b6e-29cb02b14083.log](https://github.com/alibaba/pont/files/3106235/VSIXInstaller_7f9618c5-ad6e-47ff-8b6e-29cb02b14083.log)

**Comment by icarusysuper** [comment]
![image](https://user-images.githubusercontent.com/3395277/56889031-04421380-6aa8-11e9-97ef-31ac6b100b01.png)

win7系统 vscode1.33.1 安装失败

**Comment by pfzhengd** [comment]
同问！

**Comment by jasonHzq** [comment]
已修复
