### ISSUE TITLE
Pont Roadmap: 2020

### ISSUE THREAD

**Issue by jasonHzq** [alibaba/pont#5]
## 建设模板中心，内置 generator
* 1、内置不同框架，语言的 template，让用户来选。一方面降低用户使用成本，一方面把模板最佳实践分享出来，充分发挥 pont 优势。内置 React 模板提供 hooks 接口，提供接口 preload 能力。
* 2、fetcher 方法可配置，用户使用零成本。
* 3、把 `.ts + .d.ts` 改成 `.js + .d.ts`，以提供给 Javascript 项目使用。让 Javascript 项目也可以使用 pont 并享受类型。
* 4、代码懒生成 (现在是全量删除后所有文件重新生成)
* 5、吸引社区共享共建模板。
* 6、内置支持 Js、Android Java、Angular Ts，Redux Ts, Vue Nuxt Ts 等常用语言和框架的接口层生成

## 接入更多数据源类型。
- Swagger 1.x；Swagger 3.x 已接入
- mtop 接入。

## Mock平台及接口测试平台，完善 Pont 生态。
- 开放基于 pont 的 mocks 平台及测试平台。

## 补充自动化测试
- 当前测试用例过少。需要增加。

**Comment by jasonslyvia** [comment]
催更催更 😎

**Comment by jasonHzq** [comment]
> 催更催更 😎

你们也有用吗

**Comment by jasonHzq** [comment]
添加优化项：

* Swagger 接口无法访问精准报错。

**Comment by MicahZJ** [comment]
等着接入webstorm

**Comment by kwzm** [comment]
期待 mtop 的接入，有具体时间吗
