### ISSUE TITLE
又造了个轮子ts-gear

### ISSUE THREAD

**Issue by superwf** [alibaba/pont#50]
感谢分享pont。
刚使用pont的时候，有的地方会有使用pontFetch方法，但找不到从哪里引入的。
所以只使用了生成的baseClass。
目前新版本里这个问题已经修正了。

经过一段时间pont的使用有一些地方做了针对自己项目的更改，后来越改越多偏的太多了。
所以没有提pr。
又造了一个类似pont的轮子起名叫[ts-gear](https://github.com/superwf/ts-gear)，在自己的项目里还挺好用。

没有继续用pont中生成一个大namespce的思路，直接生成带参数与返回数据类型校验的每个接口的请求方法函数。
每个子项目里带一个interceptor.ts可以定制请求与返回数据类型。
望参考有用的功能合并。

**Comment by jasonHzq** [comment]
生成的代码，自定义模板可以完全定制配置的。。可以从你自己的项目里引，也可以改模板。README 文档说的还是比较清楚的。
