### ISSUE TITLE
pont读取远程接口失败的问题泛型<T>

### ISSUE THREAD

**Issue by Git911** [alibaba/pont#57]
![image](https://user-images.githubusercontent.com/34928381/59893828-c5c63680-9410-11e9-8a17-f77bdf47646a.png)

**Comment by Git911** [comment]
![image](https://user-images.githubusercontent.com/34928381/59893887-176ec100-9411-11e9-8305-4f03cee2c031.png)

**Comment by Git911** [comment]
拉取服务的时候就这样

**Comment by linningmii** [comment]
可以提供一下异常的demo项目吗？

**Comment by Git911** [comment]
那个是项目啊，
![image](https://user-images.githubusercontent.com/34928381/59985967-18992b80-9667-11e9-8d20-37802981fc31.png)
接收参数封装的：
![image](https://user-images.githubusercontent.com/34928381/59985991-39618100-9667-11e9-9ae2-9adc2ee25202.png)

**Comment by linningmii** [comment]
Pont不支持在ApiModel中的value定义Model<T>  <>会被当做非法字符导致编译失败
