### ISSUE TITLE
点击generte和sync生成数据错误。

### ISSUE THREAD

**Issue by ShawDanon** [alibaba/pont#60]
点击generte提示
TypeError: Cannot read property 'dataSource' of undefined
点击sync提示
Error: 读取远程接口数据失败！Error: compiler error in defname: PagingData«结算单(日结)»

**Comment by ShawDanon** [comment]
npm 同步错误Error: Command failed: yarn add -D pont-engine@0.2.2 (node:10259) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification. error An unexpected error occurred: "http://registry.npm.alibaba-inc.com/ts-node/download/ts-node-3.3.0.tgz: ETIMEDOUT".

**Comment by linningmii** [comment]
能提供一下swagger的api-docs吗

**Comment by loveholly** [comment]
`PagingData«结算单(日结)»` 这个是非标准的JSON格式(«)，在pont这边解析的时候会报错，解决方案是生成swagger的时候，给泛型做特殊处理，具体查各自框架的设置
