### ISSUE TITLE
Ubuntu下插件无法运行

### ISSUE THREAD

**Issue by Houcer** [alibaba/pont#65]
Ubuntu18，vscode1.36.1下，安装之后底部没有出现按钮。打开code的开发人员工具，console里报错 `can not find module './UI'`。
插件安装包`~/.vscode/extensions/jasonhzq.vscode-pont-0.2.3/out`路径下只有一个小写的`ui.js`，我把文件名改成大写的`UI.js`之后，插件就正常运行了。

**Comment by jasonHzq** [comment]
插件上已修复
