### ISSUE TITLE
运行 pont check格式化出错

### ISSUE THREAD

**Issue by ShawDanon** [alibaba/pont#75]
![图片](https://s2.ax1x.com/2019/07/21/e9Zp4g.png)

**Comment by linningmii** [comment]
这个应该是export占用了ts关键字导致的语法报错，尝试修改一下模块名称？

**Comment by ShawDanon** [comment]
是的，关键字占用我想的是在取名字的时候弄个枚举做关键字转换来着

**Comment by jasonHzq** [comment]
> 是的，关键字占用我想的是在取名字的时候弄个枚举做关键字转换来着

这个有做。我们再丰富一下

**Comment by qixm-burnish** [comment]
这个问题到现在都没解决
