### ISSUE TITLE
关于swagger v2 元数据解析问题

### ISSUE THREAD

**Issue by ShawDanon** [alibaba/pont#76]
如图
![](https://s2.ax1x.com/2019/07/22/eCq1Ff.png)
![](https://s2.ax1x.com/2019/07/22/eCq8fS.png)

**Comment by ShawDanon** [comment]
缺少optional会解析为空字符串

**Comment by jasonHzq** [comment]
会有什么不好的结果吗？

**Comment by jasonHzq** [comment]
有enum的，typeName 不需要
