### ISSUE TITLE
Support basePath

### ISSUE THREAD

**Issue by loveholly** [alibaba/pont#84]
鉴于swagger V2是支持`basePath`的设置的，但是`pont`目前缺少这个`feature`，关于`basePath`的解释如下：

![image](https://user-images.githubusercontent.com/5133856/63148360-880e1480-c033-11e9-936f-4d9e78f47689.png)

[官方文档](https://swagger.io/docs/specification/2-0/api-host-and-base-path/)

**Comment by loveholly** [comment]
解决方案有二：
- 在`parseSwaggerMods`的时候将`basePath`和`path`进行拼接
- 在生成代码的时候将`basePath`和`path`进行拼接

@jimliang @jasonHzq @gaoletian  大家觉得哪种方案更好？我个人倾向于方案二，理由是不改变元数据，而只改变消费数据的方式

**Comment by loveholly** [comment]
经确认，最终生成的`api-lock`文件里面其实是有`basePath`属性，只是数据结构里面没有类型描述，所以考虑先加一下`basePath`的类型描述，在生成代码的时候再做拼接了。

**Comment by jasonHzq** [comment]
请问需要basePath做什么呢？ 如果是接口 url 的拼接，完全可以写在业务方的公共请求方法内部。

**Comment by xxbld** [comment]
有需要的！！！现在requeset里只有paths的部分没有添加上basePath;我有十几个这种swagger,basePath不一样，ip端口一样，公共请求没法封装啊;
![image](https://user-images.githubusercontent.com/13309211/63846091-ad990780-c9bd-11e9-9eeb-37f813250943.png)

**Comment by xxbld** [comment]
> 有需要的！！！现在requeset里只有paths的部分没有添加上basePath;我有十几个这种swagger,basePath不一样，ip端口一样，公共请求没法封装啊;
> ![image](https://user-images.githubusercontent.com/13309211/63846091-ad990780-c9bd-11e9-9eeb-37f813250943.png)

我现在的做法是用projectAssess做datasource Name,重写getInterfaceContent方法取name转/project/assess + path；
勉强可以使用。。。。
