### ISSUE TITLE
[WIP]考虑将现有 pont 生态整合为 monorepo?

### ISSUE THREAD

**Issue by inJs** [alibaba/pont#87]
整合后更有益于项目的整体维护。据我目前了解，应该有以下几部分：

+ [pont-engine](https://github.com/alibaba/pont)
+ pont-fetch
+ pont-cli
+ [vscode-pont](https://github.com/nefe/vscode-pont)

如有遗漏，烦请补充。

**Comment by linningmii** [comment]
欢迎热心同学PR！

**Comment by gaoletian** [comment]
同意

**Comment by inJs** [comment]
进展同步：【投票中】---> [方案制定] ---> [迁移]

**Comment by inJs** [comment]
逛 [vscode-pont](https://github.com/nefe/vscode-pont) 的时候发现了一个新问题：目前这种离散的方式不适合 issue 的管理。

**Comment by inJs** [comment]
## pont 生态 mono 改造方案

#### 背景

目前 pont 生态共有 **2** 个仓库：

- [alibaba/pont](https://github.com/alibaba/pont) ， 包含 CLI、pont-fetch、pont-engine 三部分
- [nefe/vscode-pont](https://github.com/nefe/vscode-pont) ，pont 的 vscode 插件

存在的几点问题：

- 仓库离散导致 issue 管理的困难。比较鲜明的例子是， alibaba/pont 仓库中的  issue 及 PR 的热度远高于 nefe/vscode-pont
- 手动维护 `vscode-pont` 与 `pont-engine` 的依赖关系
- 手动维护 版本变更、CHANGELOG  等



#### 方案

【阶段 1】 **使用 [lerna](https://github.com/lerna/lerna) 进行 mono 改造。** 具体步骤如下：

1. 在 `alibaba/pont` 下创建分支 `refactor/mono`
2. 新建目录 `temp` 并将根目录所有文件(夹) 迁移至 `temp` 下 
3. 在 **项目根目录** 下执行 lerna 初始化命令：`lerna init` 。初始化成功后，应该会生成以下文件：
   1. `lerna.json` ：配置文件
   2. `package.json` ：工程描述文件
   3. `packages` ：文件夹
4. 在 `packages` 文件夹下新建文件夹：`core` 、`vscode-plugin` 
5. 将 **temp** 下所有文件及文件夹（`packages` 除外）移动至 `packages/core` 下
6. 将 `nefe/vscode-pont` 所有的文件及文件夹迁移至 `alibaba/pont` 的 `packages/vscode-plugin` 下
7. `nefe/vscode-pont` 标记废弃，并添加至 `alibaba/pont` 的外链
8. done



【阶段 2】抽离 `core` 与 `vscode-plugin` 的公共依赖至根目录的 `package.json` 。这一步主要解决各个包之间的公共依赖的问题，进行这一步时再细化方案。

【阶段 3】从 `core` 中分离出 `pont-fetch` 与 `pont-cli` 。进行这一步时再细化方案。



#### 总结

以上为迁移步骤， 迁移完成后基本可解决：issue 管理、版本管理、CHANGELOG 等问题。

**Comment by linningmii** [comment]
> ## pont 生态 mono 改造方案
> #### 背景
> 目前 pont 生态共有 **2** 个仓库：
> 
> * [alibaba/pont](https://github.com/alibaba/pont) ， 包含 CLI、pont-fetch、pont-engine 三部分
> * [nefe/vscode-pont](https://github.com/nefe/vscode-pont) ，pont 的 vscode 插件
> 
> 存在的几点问题：
> 
> * 仓库离散导致 issue 管理的困难。比较鲜明的例子是， alibaba/pont 仓库中的  issue 及 PR 的热度远高于 nefe/vscode-pont
> * 手动维护 `vscode-pont` 与 `pont-engine` 的依赖关系
> * 手动维护 版本变更、CHANGELOG  等
> 
> #### 方案
> 【阶段 1】 **使用 [lerna](https://github.com/lerna/lerna) 进行 mono 改造。** 具体步骤如下：
> 
> 1. 在 `alibaba/pont` 下创建分支 `refactor/mono`
> 2. 新建目录 `temp` 并将根目录所有文件(夹) 迁移至 `temp` 下
> 3. 在 **项目根目录** 下执行 lerna 初始化命令：`lerna init` 。初始化成功后，应该会生成以下文件：
>    
>    1. `lerna.json` ：配置文件
>    2. `package.json` ：工程描述文件
>    3. `packages` ：文件夹
> 4. 在 `packages` 文件夹下新建文件夹：`core` 、`vscode-plugin`
> 5. 将 **temp** 下所有文件及文件夹（`packages` 除外）移动至 `packages/core` 下
> 6. 将 `nefe/vscode-pont` 所有的文件及文件夹迁移至 `alibaba/pont` 的 `packages/vscode-plugin` 下
> 7. `nefe/vscode-pont` 标记废弃，并添加至 `alibaba/pont` 的外链
> 8. done
> 
> 【阶段 2】抽离 `core` 与 `vscode-plugin` 的公共依赖至根目录的 `package.json` 。这一步主要解决各个包之间的公共依赖的问题，进行这一步时再细化方案。
> 
> 【阶段 3】从 `core` 中分离出 `pont-fetch` 与 `pont-cli` 。进行这一步时再细化方案。
> 
> #### 总结
> 以上为迁移步骤， 迁移完成后基本可解决：issue 管理、版本管理、CHANGELOG 等问题。

不知道github对subtree或者submodule支持怎么样，初期是否可以考虑从sub module开始，把构建环节放在pont仓库中

**Comment by inJs** [comment]
> 不知道github对subtree或者submodule支持怎么样，初期是否可以考虑从sub module开始，把构建环节放在pont仓库中
@linningmii 我认为 **没有必要** 使用 `submodule` 或 `subtree`，原因是 目前 `pont` 生态只有 `nefe/vscode-pont` 真实的独立了出去。而 `pont-fetch`、`pont-cli` 耦合在  `alibaba/pont` 中。迁移成本挺低的。
