### ISSUE TITLE
我有一些类似xxx/export方法,生成出来保留字会报错，请问有办法剔除这些方法嘛？

### ISSUE THREAD

**Issue by xxbld** [alibaba/pont#89]
transformPath不生效呀；
![image](https://user-images.githubusercontent.com/13309211/63908390-9e639980-ca51-11e9-9b4a-bd2920e8be33.png)

**Comment by linningmii** [comment]
transformPath使用相对路径目前看起来有点问题，建议各位先使用绝对路径

**Comment by xxbld** [comment]
> transformPath使用相对路径目前看起来有点问题，建议各位先使用绝对路径
提供一下解决方法
![TIM图片20190829162059](https://user-images.githubusercontent.com/13309211/63923377-109ba480-ca79-11e9-8c7b-792aaca7d0c0.png)
