### ISSUE TITLE
在 transformPath 中剔除不需要的Controller ,还会生成对应的文件夹

### ISSUE THREAD

**Issue by xxbld** [alibaba/pont#98]
1.在 transformPath 中剔除不需要的Controller ,还会生成对应的文件夹
2. transformPath 必须使用绝对路径;
`
export default function (dataSource: StandardDataSource): StandardDataSource {
    dataSource.mods = dataSource.mods.filter(mod => !mod.name.includes('xxxx'))
return dataSource；
}
`

**Comment by linningmii** [comment]
我本周抽空看下

**Comment by jasonHzq** [comment]
提供下对应的Swagger 数据？没有出现类似问题。

**Comment by Leon1Zhu** [comment]
第一点未复现
第二点已做优化

**Comment by xxbld** [comment]
> 第一点未复现
> 第二点已做优化

不好意思啦，当时写的测试代码丢失了；现在未出现第一种情况，那么可以关闭这个issues了
